# render.yaml

services:
  - name: Food-recipe app
    type: web
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 4 -b 0.0.0.0:$PORT your_app_module:app
    env:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: capstone1  # Replace with your actual database name
          property: connectionString


